honeycombio/hpsf

- cmd/main.go
- pkg/yaml/dottedconfig.go
- Calculates an md5 hash of the things that are being rendered. It is currently not exposed anywhere, but it's compatible with Refinery's hash calculation.
- Add hash generation
- Change API to return it with a YAML render
- adjust main
> feat: Calculate hash

- go.mod
Setting this to minimum go 1.23 version to be consistent with other repositories.
> maint: update go.mod min version

- pkg/config/refinery.go
- pkg/translator/translator.go
- Refinery Configs generated by hpsf didn't work without layering them onto another config. This gives us a way to generate something
- Add a base refinery component with the minimum fields for a valid config file
- Use it automatically as the first component when building the configs
> feat: Add base component for valid configs

- pkg/hpsf/hpsfTypes.go
- pkg/validator/validator.go
- Add solution for easily checking if an input string is valid HPSF
- Add new `EnsureHPSF` to allow easily checking if a string is valid HPSF
- Update Validator interface to return `error` instead of `[]error` to make Validate work easier with Go's typical `if err == nil` pattern.  
- Keep the ability to report multiple errors at once using `errors.Join()`
> feat: Add EnsureHPSF function

- cmd/hpsf/main.go
- pkg/config/collectorTemplate.go
- pkg/config/component.go
- pkg/config/components/OTelGRPCReceiver.yaml
- pkg/config/components/OTelHTTPReceiver.yaml
- pkg/config/components/emaThroughput.yaml
- pkg/config/components/honeycombExporter.yaml
- pkg/config/dotTemplate.go
- pkg/config/helpers.go
- pkg/config/loadComponents.go
- pkg/config/refinery.go
- pkg/config/templateComponent.go
- pkg/config/tmpl/collectorconfig.go
- pkg/config/tmpl/collectorconfig_test.go
- pkg/config/tmpl/dottedconfig.go
- pkg/config/tmpl/dottedconfig_test.go
- pkg/config/tmpl/templateconfig.go
- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfTypes_test.go
- pkg/translator/translator.go
- Ability to generate a collector config
- A couple of collector components
- Add a lot of comments
- Reorganize for easier maintenance
- Render is now RenderToMap
- The user's HPSF is now available to the template and used
- Some refinery-specific stuff is now more generic
- Additional config type for collector
- Remove the generated hash because it's not solving the right problem
- We should be using text/template not html/template
- Two collector components (that will be merged in a future PR)
- Lots of comments added
The code in this PR is functional and runs to completion, but it's not correct yet. It was just a plausible place to stop. #13 builds on this one.
> feat: a bunch of refactoring and beginnings of collector support

- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfTypes_test.go
Component properties no longer expect the property type to be set by the user authoring HPSF.
* Remove the check for declared property type.
* Add check for presence of a property name.
* Add check for presence of a property value.
* Add check that a given property value must be a string, int, or bool.
* Add a very simple initial test for validation.
> fix: replace validations for user-declared property types

- go.mod
- go.sum
- pkg/config/templateComponent.go
- pkg/translator/testdata/simple_collector_config.yaml
- pkg/translator/testdata/simple_hpsf.yaml
- pkg/translator/translator_test.go
- Correcting the emitted collector config.
- add a test for collector config output
- currently depends on #15 for the addition of testify to go dependencies
- remove duplicate section from config key templating
Changes collector config output from ...
receivers:
receivers:
otlp/x:
... to ...
receivers:
otlp/x:
- use the collector component Name property
Reference the instance property Name when rendering a component instance
instead of the name of the component type.
1. This is clearer in the rendered config. Items have the names
humans gave them.
2. Avoids naming collisions for HPSF that have two or more of the
same type of component.
Turns ...
receivers:
otlp/otlp_receiver:
... into ...
receivers:
otlp/otlp_in:
> fix: remove duplicate collector section declarations

- pkg/config/components/OTelGRPCExporter.yaml
- pkg/translator/testdata/simple_collector_config.yaml
- The collector config for otlpexporter we were generating was using the wrong schema. It doesn't need `protocols.grpc.`.
- Removed wrong schema
- updated test expectation
> fix: remove incorrect otlp export config

- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfTypes_test.go
- This ensures validates doesn't fail on maps, in support of the Headers field.
- add `map[string]any` as a valid type to the validation function.
> fix: ensure validate supports map[string]

- pkg/config/collectorTemplate.go
- pkg/config/components/OTelDebugExporter.yaml
- pkg/config/components/OTelGRPCExporter.yaml
- pkg/config/components/OTelGRPCReceiver.yaml
- pkg/config/components/OTelHTTPExporter.yaml
- pkg/config/components/OTelHTTPReceiver.yaml
- pkg/config/components/OTelReceiver.yaml
- pkg/config/components/deterministicSampler.yaml
- pkg/config/components/emaThroughput.yaml
- pkg/config/components/honeycombExporter.yaml
- pkg/config/dotTemplate.go
- pkg/config/helpers.go
- pkg/config/loadComponents_test.go
- pkg/config/templateComponent.go
- pkg/config/testdata/DeterministicSampler_output_refinery_rules.yaml
- pkg/config/testdata/EmaThroughput_output_refinery_rules.yaml
- pkg/hpsf/hpsfTypes.go
- pkg/translator/testdata/default_refinery_rules.yaml
https://app.asana.com/0/1208469935858869/1209310061786981
- Syntax has changed some for component templates since some were written. 
- HPSF was coercing everything to strings, which caused problems. We really wanted to handle normal datatypes.
- Update template syntax
- Add tests
- Allow all (most?) of the places to have actual data types and allow the templates to express them. We might be able to do still better, but what we have here now works pretty well.
- Fix the templates and tests to do the right things
> fix: handle non-string properties in components and update them

- pkg/config/components/FilterProcessor.yaml
- pkg/config/helpers.go
- pkg/config/templateComponent.go
- Nested maps were getting mangled by the map encoder. 
- This was caught in tests -- except that that test wasn't running on my VS Code test runner OR in branch testing for some reason, so the failure leaked into main. It's working in both places now. I don't know why it failed.
- Change map->string encoding from simple and hand-coded to a JSON encoding.
> fix: Fix encoding of map to handle nesting

- pkg/config/components/TraceConverter.yaml
- pkg/config/templates/emathroughput.yaml
- pkg/config/templates/proxy.yaml
- This provides the content of 2 initial template configurations for use in the UI. These will end up being moved to a database eventually.
- We're planning to also have a template for sending things to cold storage (and eventually many more) but we don't have the components to support that yet.
- Proxy template
- EMA Throughput template
- TraceConverter component improved
> feat: First 2 templates for configurations

- .gitignore
- Makefile
- testTemplate.sh
- easy way to generate configs from templates
- easy way to validate configs
- Add make targets for `validate` and `test_template` 
- Generated configs from templates get placed in tmp/ directory that is gitignored
Example usage
```sh
make test_template TEMPLATE=pkg/config/templates/proxy
make validate CONFIG=examples/hpsf2.yaml
```
> maint: add make targets for validating configs

- Makefile
- examples/hpsfProxy.yaml
- internal asana task https://app.asana.com/0/1208469935858869/1209503664352030
- add example that demonstrates basic property overrides for proxy template (otlp collector) 
- add Makefile target for smoke and unsmoke that simply generates the collector config from the proxy template and tries to run it in Docker. This isn't in CI yet but can be run locally.
**Note**: When this is generated it uses the "Name" field in the collector config. If the name has spaces it will be invalid in Collector config. We'll want to normalize that but maybe as a follow-up. We can use this example for testing.
For example, `otlp/MyCompany OTel Receiver` should become something like `otlp/MyCompany_OTel_Receiver`
This can be confirmed with a quick run in docker (basic "smoke" test added, name tbd):
```sh …
```
> maint: add proxy example and test for collector config

- Makefile
- cmd/hpsf/main.go
- examples/hpsf.yaml
- examples/hpsfBig.yaml
- pkg/config/templateComponent.go
- pkg/data/components/EmaThroughput.yaml
- pkg/data/components/OTelGRPCExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/OTelReceiver.yaml
- pkg/data/components/TraceConverter.yaml
- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfTypes_test.go
- pkg/translator/translator.go
- Cleaning up the validation logic
- Fix up property types (number -> int and float, add map)
- Adjust property definitions in various places
- Add validation for names of top-level keys in HPSF files
- Adjust makefile to check templates as well as examples
> fix: Improvements to validation

- pkg/data/components/DeterministicSampler.yaml
- pkg/data/testdata/DeterministicSampler_output_refinery_rules.yaml
- pkg/translator/testdata/default_refinery_rules.yaml
- Deterministic Sampler should use SampleRate, not GoalThroughput
- Update DeterministicSampler component to look at SampleRate
- Update expected default refinery rules
> fix: deterministic sampler should use SampleRate

- pkg/config/helpers.go
- pkg/config/templateComponent.go
- pkg/data/components/EmaThroughput.yaml
- pkg/data/components/HoneycombExporter.yaml
- pkg/data/components/OTelGRPCExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/OTelReceiver.yaml
- pkg/data/components/TraceConverter.yaml
- TemplateComponents now have a Comment property
- Several of the common components now have some of their properties marked with the Advanced flag
The advanced flag is an indication that most configurations will not need to modify that property, so it is hidden by default in the UI under a control that looks like "> Advanced". Clicking that control will reveal all those properties. It's intended to allow components to have a lot of configurability but to hide it from the average user.
- Add comment field to TemplateComponent
- delete unused function that was mistakenly committed
- Mark some properties as Advanced
> feat: add comment property, use advanced property

- cmd/hpsf/main.go
- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfTypes_test.go
- pkg/validator/validator.go
- The validation routine as written returned []error. That's both nonidiomatic and also awkward.
- This creates a new hpsf.Error type that can be either a warning or an error, and contains location detail
- And also revises the validation.Error type to validation.Result -- which is a collection of errors 
- And then uses them; we have no warnings yet but we'll get there
- Minor tweaks to validation code
- Add a test for failing validations to make sure the system works as advertised
This PR will require changes to hound once it merges -- there are breaking changes to the validate functions. I'll get to those next.
> feat: new error types

- pkg/data/components/NopExporter.yaml
- pkg/data/components/NopReceiver.yaml
- pkg/data/components/OTelDebugExporter.yaml
- Ensures nop receiver/exporter and for the debug exporter can be connected for all signals.
- This adds all the signals for the nop receiver/exporter and for the debug exporter.
> feat: add metrics/logs to nop components, all signals to debug exporter

- pkg/data/components/TraceConverter.yaml
- The TraceConverter was producing invalid configuration.
- Updated the template to only use HTTP for export
> bugfix: trace converter must support one of http or grpc

- pkg/data/components/TraceConverter.yaml
These fields are needded to be able to configure the exporter w/ all the right fields.
> feat: add headers/insecure support for TraceConverter

- pkg/translator/translator.go
- pkg/translator/translator_test.go
- This adds support to the translator to return contents of templates as well as components it currently supports.
- added `InstallTemplates` func to translator
- applied the suggestion to use `maps.Copy` instead of looping through the maps
- updated the test to include loading templates and installing them
- add GetComponents & GetTemplates funcs
> feat: add InstallTemplates func

- pkg/hpsf/hpsfTypes.go
- pkg/translator/translator.go
- pkg/translator/translator_test.go
When generating configs, if no sampler component is provided the translator does not produce a valid refinery rules configuration (no default sampler).
This PR updates the sampler to check if a sampler was provided in the list of components, and if not, adds a default deterministic sampler with a sample rate of 1.
- Add style property to hpsf.Component
- Add `maybeAddDefaultSampler` that checks if there the components contains a sampler and adds one if not
- Add unit test
> fix: Translator generates valid refinery rules when no sampler component is provided

- pkg/data/loadEmbedded.go
- pkg/data/loadEmbedded_test.go
- pkg/data/templates/default.yaml
- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfTypes_test.go
- pkg/translator/testdata/default_collector_config.yaml
- pkg/translator/testdata/default_refinery_rules.yaml
- pkg/translator/translator_test.go
Updates the default HPSF config to use the embedded proxy template.
- Add new default template (copy of proxy)
- Add LoadEmbeddedDefaultTemplate and DefaultConfigurationKind that can be used to retrieve the default template
- Move default config test from hspf to data package
- Add AsYAML func to hspf type (same as we use for TemplateComponent)
- Update translator tests for expected default config to match proxy template output
> feat: Update the default template to be a complete embedded template

- pkg/data/components/DeterministicSampler.yaml
- pkg/data/components/FilterProcessor.yaml
- pkg/data/components/HoneycombExporter.yaml
- pkg/data/components/NopExporter.yaml
- pkg/data/components/NopReceiver.yaml
- pkg/data/components/OTelDebugExporter.yaml
- pkg/data/components/OTelGRPCExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/OTelReceiver.yaml
- pkg/data/components/TraceConverter.yaml
- Receivers and Exporters need to name a logo to show up in the UI. This adds those logos.
- Also adjusts some descriptions to be clearer and less redundant
- The TraceConverter is not an "exporter" in the straws sense (it is for collector but in straws it's a type of processor)
> feat: Add logos to receivers and exporters, tweak some text

- pkg/data/components/S3Exporter.yaml
- pkg/translator/testdata/collector_config/s3exporter_all.yaml
- pkg/translator/testdata/collector_config/s3exporter_defaults.yaml
- pkg/translator/testdata/hpsf/s3exporter_all.yaml
- pkg/translator/testdata/hpsf/s3exporter_defaults.yaml
Adds the a new HPSF component for the OTel Collector [S3 Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/awss3exporter).
The only required property is `Bucket`, all others have default values assumed from the collector component.
- https://app.asana.com/0/1208469935858869/1208531739378699/f
- Add new component definition
- Add default and all test data files to verify expected output
> feat: Add S3 exporter component

- pkg/config/templateProperty.go
- pkg/data/components/FilterProcessor.yaml
- pkg/data/components/HoneycombExporter.yaml
- pkg/data/components/LogDeduplicationProcessor.yaml
- pkg/data/components/OTelDebugExporter.yaml
- pkg/data/components/OTelGRPCExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/OTelReceiver.yaml
- pkg/data/components/S3Exporter.yaml
- pkg/data/components/TraceConverter.yaml
- pkg/hpsf/hpsfTypes_test.go
- pkg/translator/testdata/collector_config/honeycombexporter_all.yaml
- pkg/translator/testdata/collector_config/honeycombexporter_defaults.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
- pkg/translator/testdata/refinery_config/honeycombexporter_all.yaml
- pkg/translator/translator_test.go
- pkg/validator/validator.go
Component validations are not currently being applied. This update applies property validation and updates the components where necessary to conform to their validations.
- Update TemplateComponent's yaml name to so they are loaded into the component
- Use the property value, not type, when trying to coerce the value before applying a validation
- Update each components validations definition to use a yaml list instead of inline array which can cause issues when parsing strings
- Update HoneycombExporter testdata to set a valid URL
- Update Validation.Result's Unwrap to return a single error instead of an []error
- The docs say []error should be okay, but it fails the [interface check](https://github.com/golang/go/blob/master/src/errors/wrap.go#L17) and always returned nil
- Remove filter …
> maint: Apply component property validations

- pkg/data/components/OTelGRPCExporter.yaml
- this is used in default so it needs to be alpha
- set OTelGRPCExporter to alpha status
> feat: set otelgrpc exporter to alpha

- pkg/data/templates/default.yaml
- pkg/translator/testdata/collector_config/default.yaml
- sometimes http is easier to work with
- use OTelHTTPExporter in default instead of gRPC
> feat: use http exporter in default

- pkg/data/templates/default.yaml
- pkg/data/templates/emathroughput.yaml
- pkg/data/templates/proxy.yaml
Fixes the layouts for each of the pipeline configuration templates to be valid.
For example, the default template now renders with a valid layout
- https://app.asana.com/0/1208469935858869/1209917737059230/f
- Update each template's layout section to move the x and y coordinates into the position sub-section
- Remove frame section
> maint: Update template layouts to be valid

- pkg/translator/testdata/hpsf/deterministicsampler_all.yaml
- pkg/translator/testdata/hpsf/deterministicsampler_defaults.yaml
- pkg/translator/testdata/hpsf/emathroughput_all.yaml
- pkg/translator/testdata/hpsf/emathroughput_defaults.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_defaults.yaml
- pkg/translator/translator_test.go
Having duplicate HoneycombExporter components in the same workflow can inconsistent output Refinery config's as they compete to write the same values.
- closes #70 
- Replace duplicate HoneycombExporter components in test data workflows with TraceConverter for input streams
- Simplify the translator test loop to use the component struct in the for loop
> fix: Replace duplicate HoneycombExporter in test data

- pkg/config/templateProperty.go
- pkg/data/components/FilterProcessor.yaml
- pkg/data/components/OTelDebugExporter.yaml
- pkg/data/components/OTelGRPCExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/S3Exporter.yaml
We needed more granularity in our UI for different component types. This adds a subtype field that can be used to feed extra information to select better editors.
- for maps, subtype 'header' changes the default text in the map editor
- for strings, subtype 'oneof(a, b, c)' creates a dropdown with values a, b, and c
- Add `subtype` to templateProperty
- Add subtype entries to components as appropriate
- Fix S3 component to specify its documented defaults (also correct some text)
To see this in the product will require a release of HPSF and a poodle PR.
> feat: add subtype to components

- pkg/config/dotTemplate.go
- pkg/config/helpers.go
- pkg/data/components/HoneycombExporter.yaml
- pkg/data/testdata/HoneycombExporter_output_refinery_config.yaml
- pkg/translator/testdata/refinery_config/honeycombexporter_all.yaml
- This allows refinery to use the configured API key instead of the one present in the headers.
- added tests for presence of the API key and when it's not present
- ensure `suppress_if` is respected for all types of config
- updated honeycomb exporter with SendKeyMode template
> feat: set SendKeyMode when api key present

- Makefile
Adds integration tests to verify each refinery component can generate config and rules files that a refinery docker image can start with.
- https://app.asana.com/1/72322038700732/project/1208469935858869/task/1209503669851437?focus=true
> feat: Add smoke tests for refinery components

- pkg/data/templates/default.yaml
- pkg/translator/testdata/collector_config/default.yaml
- closes https://github.com/honeycombio/pipeline-team/issues/250
- add default headers with env var value to the otlp exporter in the default template
> feat: add headers to default otlp exporter

- pkg/data/templates/default.yaml
- pkg/data/templates/emathroughput.yaml
- pkg/data/templates/proxy.yaml
* Fixes https://github.com/honeycombio/pipeline-team/issues/320
* The nodes are much bigger now due to this PR matching the elements to look more like the Figma design: https://github.com/honeycombio/hound/pull/23956
* The original positions in the templates were picked based on the smaller nodes, now that the new design is implemented and the nodes are bigger, it's causing the nodes to either overlap or look wonky like below:
This PR just moves the nodes in the template further apart from each other 😄 
* Default Template:
* Proxy Template:
* EMA Throughput Template:
> fix: Update component positions in templates due to bigger nodes in new design

- pkg/config/component.go
- pkg/config/rulestemplate.go
- pkg/config/templateComponent.go
- pkg/config/tmpl/collectorconfig.go
- pkg/config/tmpl/dottedconfig.go
- pkg/config/tmpl/dottedconfig_test.go
- pkg/config/tmpl/rulesconfig.go
- pkg/config/tmpl/templateconfig.go
- pkg/data/components/DeterministicSampler.yaml
- pkg/data/components/EmaThroughput.yaml
- pkg/data/components/README.md
- pkg/data/components/SampleErrors.yaml
- pkg/data/loadEmbedded_test.go
- pkg/data/testdata/EmaThroughput_output_refinery_rules.yaml
- pkg/hpsf/hpsfTypes.go
- pkg/translator/testdata/hpsf/sampleerrors_all.yaml
- pkg/translator/testdata/hpsf/sampleerrors_defaults.yaml
- pkg/translator/testdata/refinery_rules/sampleerrors_all.yaml
- pkg/translator/testdata/refinery_rules/sampleerrors_defaults.yaml
- pkg/translator/translator_test.go
- Rules files needed to be changed so that they're composable. The old way didn't work. This changes how they're generated and adds some new semantics so that we can build useful rules components. The problem is in the weirdly nested nature of refinery rules -- I wanted to avoid a structure that was tightly tied to refinery's current configuration structure but is still flexible enough to handle it. It's definitely got some rather refinery-specific code in here but it's not quite as brittle as an explicit structure.
- Add a rules_config config type (it uses dotted config but has some rules-specific fields and has extra semantics)
- Add a compact way of expressing rules conditions and a special way to handle them in the rules generator
- Add the ability to specify an index so we can create …
> feat: change the way rules files are generated

- pkg/data/components/TraceConverter.yaml
- pkg/translator/testdata/collector_config/traceconverter_all.yaml
- pkg/translator/testdata/collector_config/traceconverter_defaults.yaml
- pkg/translator/testdata/hpsf/traceconverter_all.yaml
- fixes https://github.com/honeycombio/pipeline-team/issues/383
We found the following issues with the traceconverter default install:
1. it uses the `{STRAWS_REFINERY_POD_IP}` env var that the collector does not have access to. 
2. Sets default otlp http port to 4318, but refinery listens for otlp http on port 80
3. Configures the otlphttp exporter to communicate using TLS, but Refinery is not using TLS.
4. The property is named Host, which implies a schema (http/https) does not need to be provided, but the default does not provide it.
- Updated env var to `${STRAWS_REFINERY_SERVICE}`. We'll update the helm chart to set this env var using the refinery service name it generates: https://github.com/honeycombio/helm-charts/pull/488
- update default port to 80
- update default TLS to be …
> fix: TraceConverter default values

- pkg/data/components/S3Exporter.yaml
- pkg/translator/testdata/collector_config/s3exporter_all.yaml
- pkg/translator/testdata/collector_config/s3exporter_defaults.yaml
- pkg/translator/testdata/hpsf/s3exporter_all.yaml
- closes https://github.com/honeycombio/pipeline-team/issues/318
- add configuration specific to data activation. flush timeout and batch size are configurable, but the sizer unit is not. We're using `items` instead of `bytes` based on some testing that found `bytes` was incredible inefficient in the collector.
> feat: update s3 exporter with batch config

- pkg/config/tmpl/collectorconfig.go
- pkg/config/tmpl/collectorconfig_test.go
- pkg/data/components/OTelGRPCExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/TraceConverter.yaml
- pkg/translator/testdata/collector_config/default.yaml
- pkg/translator/testdata/collector_config/filterprocessor_all.yaml
- pkg/translator/testdata/collector_config/filterprocessor_defaults.yaml
- pkg/translator/testdata/collector_config/logdeduplicationprocessor_all.yaml
- pkg/translator/testdata/collector_config/logdeduplicationprocessor_defaults.yaml
- pkg/translator/testdata/collector_config/nopexporter_all.yaml
- pkg/translator/testdata/collector_config/nopexporter_defaults.yaml
- pkg/translator/testdata/collector_config/nopreceiver_all.yaml
- pkg/translator/testdata/collector_config/nopreceiver_defaults.yaml
- pkg/translator/testdata/collector_config/oteldebugexporter_all.yaml
- pkg/translator/testdata/collector_config/oteldebugexporter_defaults.yaml
- pkg/translator/testdata/collector_config/otelgrpcexporter_all.yaml
- pkg/translator/testdata/collector_config/otelgrpcexporter_defaults.yaml
- pkg/translator/testdata/collector_config/otelhttpexporter_all.yaml
- pkg/translator/testdata/collector_config/otelhttpexporter_defaults.yaml
- pkg/translator/testdata/collector_config/otelreceiver_all.yaml
- pkg/translator/testdata/collector_config/otelreceiver_defaults.yaml
- pkg/translator/testdata/collector_config/s3exporter_all.yaml
- pkg/translator/testdata/collector_config/s3exporter_defaults.yaml
- pkg/translator/testdata/collector_config/traceconverter_all.yaml
- pkg/translator/testdata/collector_config/traceconverter_defaults.yaml
- pkg/translator/testdata/hpsf/otelgrpcexporter_all.yaml
- pkg/translator/testdata/hpsf/otelhttpexporter_all.yaml
- pkg/translator/testdata/hpsf/traceconverter_all.yaml
- This removes the need for the separate batch processor and instead uses the batching configuration on the OTLP exporters directly. It cleans up the code used to inject the batch processor.
- update templates for otel grpc/http exporters and traceconverter
- update the tests
> feat: use batch config in exporters

- pkg/config/rulestemplate.go
- pkg/data/components/KeepErrors.yaml
- pkg/data/components/KeepSlowTraces.yaml
- pkg/translator/testdata/hpsf/keeperrors_all.yaml
- pkg/translator/testdata/hpsf/keeperrors_defaults.yaml
- pkg/translator/testdata/hpsf/keepslowtraces_all.yaml
- pkg/translator/testdata/hpsf/keepslowtraces_defaults.yaml
- pkg/translator/testdata/hpsf/sampleerrors_all.yaml
- pkg/translator/testdata/hpsf/sampleerrors_defaults.yaml
- pkg/translator/testdata/refinery_rules/keeperrors_all.yaml
- pkg/translator/testdata/refinery_rules/keeperrors_defaults.yaml
- pkg/translator/testdata/refinery_rules/keepslowtraces_all.yaml
- pkg/translator/testdata/refinery_rules/keepslowtraces_defaults.yaml
- pkg/translator/testdata/refinery_rules/sampleerrors_all.yaml
- pkg/translator/testdata/refinery_rules/sampleerrors_defaults.yaml
- pkg/translator/translator_test.go
- We needed more examples of rules components
- There were some test problems with existing rules tests
- We were enforcing value's type before evaluation of templates; this was wrong. I removed it for now. A separate PR will add it back soon.
- Add some new rules components
- KeepSlowTraces
- KeepErrors
- Fix some test problems
- Test file for SampleErrors was completely wrong 
- Remove type enforcement before template expansion
> feat: new rules components

- pkg/config/helpers.go
Adds a way to convert a template parameter to Uppercase
Added `upper` as a template helper that delegates to `strings.ToUpper`
> feat(hpsf): Added an upper function to the go templates

- pkg/data/templates/emathroughput.yaml
- closes https://github.com/honeycombio/pipeline-team/issues/442
- Update to use new fields like Input -> Traces, Output -> Events, Honeycomb -> HoneycombEvents, Kept -> SampledOutput
To test the config is valid, I added an API key to the HoneycombExporter and ran `make smoke`. I might try to update that in a separate PR to add that when testing, because if we were running this in CI we would catch this.
```yaml
- name: Honeycomb Exporter 1
kind: HoneycombExporter
properties:
- name: APIKey
value: hccik_01jj2jj42424jjjjjjj2jjjjjj424jjj2jjjjjjjjjjjjjjj4jjjjj24jj # its fake no worries
```
> fix: update emathroughput template to use updated fields

- pkg/data/components/LogDeduplicationProcessor.yaml
Updates the Logs Dedup processor's ports to conform to standard naming.
- Rename LogsIn/Out to just `Logs`
> feat: Update logs dedup processor port names

- .circleci/config.yml
- Makefile
- template was broken and could've been caught sooner
* honeycomb exporter requires an API key in order to run. that is the only thing preventing these templates from running
successfully in a smoke test, so set a fake api key in the test to ensure everything else works as expected.
* This still only checks templates, not all components, so it is still quick to run but adds a ton of confidence for templates.
This would be nice to run in CI but in a quick timebox found it needed a few more things to be successful (install yq for instance). May revisit later but in the meantime this is still useful to see "will it run"
> fix: make it easier to run smoke tests for templates

- examples/hpsfComposedComponents.yaml
- pkg/data/components/StartSampling.yaml
- pkg/data/templates/emathroughput.yaml
- pkg/data/templates/s3.yaml
- pkg/translator/testdata/collector_config/startsampling_all.yaml
- pkg/translator/testdata/collector_config/startsampling_defaults.yaml
- pkg/translator/testdata/hpsf/deterministicsampler_all.yaml
- pkg/translator/testdata/hpsf/deterministicsampler_defaults.yaml
- pkg/translator/testdata/hpsf/emathroughput_all.yaml
- pkg/translator/testdata/hpsf/emathroughput_defaults.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_defaults.yaml
- pkg/translator/testdata/hpsf/keeperrors_all.yaml
- pkg/translator/testdata/hpsf/keeperrors_defaults.yaml
- pkg/translator/testdata/hpsf/samplebyhttpstatus_all.yaml
- pkg/translator/testdata/hpsf/samplebyhttpstatus_defaults.yaml
- pkg/translator/testdata/hpsf/samplebytraceduration_all.yaml
- pkg/translator/testdata/hpsf/samplebytraceduration_defaults.yaml
- pkg/translator/testdata/hpsf/startsampling_all.yaml
- pkg/translator/testdata/hpsf/startsampling_defaults.yaml
- tests/scenario_tests/keep_errors_test.go
- tests/scenario_tests/testdata/keep_errors.yaml
Rename the TraceConverter to StartSampling
Closes: https://github.com/honeycombio/pipeline-team/issues/452
Renames the component and all associated tests, also updates the summary/description and adds a new assertion in a test ensure the pipeline is created.
> feat(components): Rename TraceConverter to StartSampling

- pkg/data/components/HoneycombExporter.yaml
- pkg/data/components/OTelGRPCExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/StartSampling.yaml
Updates existing components that have a bool property to set a label name using it's subtype.
- Part of https://github.com/honeycombio/pipeline-team/issues/265
- Related to https://github.com/honeycombio/hound/pull/24759
- Updates the following components to add a label in their bool subtype property:
- StartSampling - UseTLS
- HoneycombExporter - Insecure
- OTelHTTPExporter - Insecure
- OTelGRPCExporter - Insecure
> feat: Add subtype labels for bool properties

- pkg/translator/testdata/collector_config/redactionprocessor_all.yaml
- pkg/translator/testdata/collector_config/redactionprocessor_defaults.yaml
There was an undetected merge conflict after merging the redaction processor which caused some of it's tests to fail because the logs pipeline names were different.
- Update logs pipeline names so tests pass
> fix: Update redaction component tests logs pipeline names

- pkg/data/components/StartSampling.yaml
The StartSampling's embedded label is wrong. It should be Enabled instead of Disable.
- Failing test will be fixed by https://github.com/honeycombio/hpsf/pull/137
- Update StartSampling component's UI label
> fix: Update StartSampling UseTLS label

- tests/scenario_tests/multiple_pipelines_test.go
- tests/scenario_tests/testdata/multiple_pipelines.yaml
- tests/scenario_tests/testdata/multiple_pipelines_multiple_exporters.yaml
- tests/scenario_tests/testdata/multiple_pipelines_single_exporter.yaml
- tests/scenario_tests/testdata/multiple_pipelines_sub_processors.yaml
No validation that HPSF definitions that should generate distinct pipelines is actually doing that.
This is only tests to ensure that changes don't break that functionality. These should be resilient to pipeline consolidation when that happens.
> test: Added test for the various multiple pipeline scenarios

- pkg/data/components/HoneycombExporter.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
The HoneycombExporter's APIEndpoint parameter is expected to include a port when overriding. This fails validation rules which expect no port to be provide. This PR adds a new APIPort parameter.
The following PR improves validation logic and would highly this problem:
- https://github.com/honeycombio/hpsf/pull/136
- Adds a new APIPort parameter to the HoneycombExporter component
- Update tests to use new parameter
> feat: Add APIPort parameter to HoneycombExporter

- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfValidations.go
- pkg/validator/validator.go
- This adds two syntax-level validations to HPSF. These are the validations that can be done without instantiating the actual components:
- Ensure that component names are unique (this can be caused by the user changing names in the UI)
- Ensure that connections name actual components at both ends (should not be possible if you only use the UI)
- Move some code out to a new validator file
- Add the specific tests above as individual functions
- Clean up some error code
- Fix a place where we failed to use a defined type (port direction)
> feat: Add syntax-level validations to HPSF

- examples/hpsf.yaml
- examples/hpsf2.yaml
- pkg/data/components/DeterministicSampler.yaml
- pkg/data/components/EmaThroughput.yaml
- pkg/data/components/KeepErrors.yaml
- pkg/data/components/SampleByHTTPStatus.yaml
- pkg/data/components/SampleByTraceDuration.yaml
- pkg/data/testdata/DeterministicSampler_output_refinery_rules.yaml
- pkg/data/testdata/EmaThroughput_output_refinery_rules.yaml
- pkg/translator/testdata/bad_hpsf/missing_port.yaml
- pkg/translator/testdata/hpsf/deterministicsampler_all.yaml
- pkg/translator/testdata/hpsf/emathroughput_all.yaml
- pkg/translator/testdata/hpsf/keeperrors_all.yaml
- pkg/translator/testdata/hpsf/samplebyhttpstatus_all.yaml
- pkg/translator/testdata/hpsf/samplebytraceduration_all.yaml
- pkg/translator/testdata/refinery_rules/deterministicsampler_all.yaml
- pkg/translator/testdata/refinery_rules/emathroughput_all.yaml
- pkg/translator/testdata/refinery_rules/keeperrors_all.yaml
- pkg/translator/testdata/refinery_rules/samplebyhttpstatus_all.yaml
- pkg/translator/testdata/refinery_rules/samplebytraceduration_all.yaml
- tests/scenario_tests/keep_errors_test.go
- tests/scenario_tests/testdata/keep_errors.yaml
Removes samplers environment property.
- Closes https://github.com/honeycombio/pipeline-team/issues/509
- Update samplers to remove environment property
- Update examples and tests to not set an environment
> fix: Remove environment property from samplers

- examples/hpsf.yaml
- examples/hpsf2.yaml
- pkg/data/components/DeterministicSampler.yaml
- pkg/data/components/EmaThroughput.yaml
- pkg/data/components/KeepErrors.yaml
- pkg/data/components/SampleByHTTPStatus.yaml
- pkg/data/components/SampleByTraceDuration.yaml
- pkg/data/testdata/DeterministicSampler_output_refinery_rules.yaml
- pkg/data/testdata/EmaThroughput_output_refinery_rules.yaml
- pkg/translator/testdata/bad_hpsf/missing_port.yaml
- pkg/translator/testdata/hpsf/deterministicsampler_all.yaml
- pkg/translator/testdata/hpsf/emathroughput_all.yaml
- pkg/translator/testdata/hpsf/keeperrors_all.yaml
- pkg/translator/testdata/hpsf/samplebyhttpstatus_all.yaml
- pkg/translator/testdata/hpsf/samplebytraceduration_all.yaml
- pkg/translator/testdata/refinery_rules/deterministicsampler_all.yaml
- pkg/translator/testdata/refinery_rules/emathroughput_all.yaml
- pkg/translator/testdata/refinery_rules/keeperrors_all.yaml
- pkg/translator/testdata/refinery_rules/samplebyhttpstatus_all.yaml
- pkg/translator/testdata/refinery_rules/samplebytraceduration_all.yaml
- tests/scenario_tests/keep_errors_test.go
- tests/scenario_tests/testdata/keep_errors.yaml
Reverts honeycombio/hpsf#147
This is so that we can do a release of HPSF without this breaking change.
> rel: Revert "fix: Remove environment property from samplers" 

- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/StartSampling.yaml
- pkg/translator/testdata/collector_config/default.yaml
- pkg/translator/testdata/collector_config/filterprocessor_all.yaml
- pkg/translator/testdata/collector_config/filterprocessor_defaults.yaml
- pkg/translator/testdata/collector_config/otelhttpexporter_all.yaml
- pkg/translator/testdata/collector_config/otelhttpexporter_defaults.yaml
- pkg/translator/testdata/collector_config/parseattributeasjson_all.yaml
- pkg/translator/testdata/collector_config/parseattributeasjson_defaults.yaml
- pkg/translator/testdata/collector_config/parselogbodyasjson_all.yaml
- pkg/translator/testdata/collector_config/parselogbodyasjson_defaults.yaml
- pkg/translator/testdata/collector_config/redactionprocessor_all.yaml
- pkg/translator/testdata/collector_config/redactionprocessor_defaults.yaml
- pkg/translator/testdata/collector_config/symbolicatorprocessor_all.yaml
- pkg/translator/testdata/collector_config/symbolicatorprocessor_defaults.yaml
- We updated the validators to enforce that the Host property is a host or IP, like we wanted, but we also needed to update the template to set the scheme since it was no longer settable via the Host property.
The otlp http exporter now sets the http scheme based on the `insecure` property. This follows the same strategy the StartSampling component uses.
- Update OTLP HTTP exporter component to set an http scheme based on Insecure propty.
- Update template to use `.Values`.
- Update tests.
> fix: automatically set otlp http exporter scheme based on insecure

- pkg/data/components/NopReceiver.yaml
- pkg/data/components/OTelReceiver.yaml
- related to https://github.com/honeycombio/pipeline-team/issues/526
- Update all the receivers components to match naming decisions from https://honeycomb.quip.com/EtZVAykv9zYU/HPSF-Component-Naming-Refactor-Discussion
> maint: rename receivers components to match naming guidelines

- tests/scenario_tests/sampling_first_pipe_test.go
- tests/scenario_tests/sampling_two_pipes_test.go
- tests/scenario_tests/testdata/firstSamplingPipe.yaml
- tests/scenario_tests/testdata/twoSamplingPipes.yaml
- The new refinery stuff didn't have any scenario tests. This adds two of them
- The scenarios were ones I built during my manual testing. I had cursor help me write the test code that validates them, then hand-inspected it. It's pretty specific, but seems correct.
> maint: Add a couple of Refinery scenario tests

- pkg/config/rulestemplate.go
- pkg/config/tmpl/rulesconfig.go
- pkg/data/components/SamplerDrop.yaml
- pkg/data/components/SamplerKeepAll.yaml
- pkg/translator/testdata/refinery_rules/dropper_all.yaml
- pkg/translator/testdata/refinery_rules/dropper_defaults.yaml
- pkg/translator/testdata/refinery_rules/errorexistscondition_all.yaml
- pkg/translator/testdata/refinery_rules/errorexistscondition_defaults.yaml
- pkg/translator/testdata/refinery_rules/httpstatuscondition_all.yaml
- pkg/translator/testdata/refinery_rules/httpstatuscondition_defaults.yaml
- pkg/translator/testdata/refinery_rules/longdurationcondition_all.yaml
- pkg/translator/testdata/refinery_rules/longdurationcondition_defaults.yaml
- tests/scenario_tests/sampling_first_pipe_test.go
- tests/scenario_tests/sampling_two_pipes_test.go
- When generating HPSF rules for Refinery, it wasn't generating the Name field for the rules. This uses the sampler name as the rule name so that the rules can be documented. Since the names must be unique, this is safe and helpful.
- Pass the component name into the metadata
- When conditions are right, use the component name to extend the data for the rules
- Fix all the tests to look for rule names
- The keep and drop samplers had a RuleName field that wasn't being used or tested for. Remove it.
> feat: Use the sampler name as the rule name when generating refinery configs

- pkg/config/tmpl/rulesconfig.go
- tests/scenario_tests/sampling_first_pipe_test.go
- tests/scenario_tests/testdata/firstSamplingPipe.yaml
- #170 had added using the sampler name for the rule name, but I forgot to properly account for downstream samplers (the refinery configuration for samplers is complex!). This fixes that problem.
- make shouldAddNameField() more restrictive
- handle downstream samplers specifically
- tweak the firstSamplingPipe scenario test to use a downstream EMA instead of KeepAll to test for this case
Had quite a bit of help from Cursor AI on this one.
> fix: Set the name field properly with downstream samplers

- pkg/config/templateComponent.go
- pkg/config/tmpl/rulesconfig.go
- tests/scenario_tests/sampling_direct_downstream_test.go
- tests/scenario_tests/testdata/sampling_direct_downstream.yaml
- A path that contained a complex sampler but no conditions didn't render properly
- Write a good test (thanks for the assist, Cursor)
- Propagate the index to the right place
- Clean up the output so it renders idiomatically (curse you, Refinery rules config!)
> fix: handle paths with just a complex sampler

- Makefile
- pkg/data/templates/emathroughput.yaml
- tests/smoke/everything_alpha.yaml
- Closes https://github.com/honeycombio/pipeline-team/issues/306
- Update smoke tests to uses the supervised-collector image.
- Update smoke tests to handle new unique pipeline names
- Update EMAThroughput sampler to latest sampler API
- add test that smokes all alpha components and their properties.
I tried adding `make smoke` to CI but passing the config files to docker is proving challenging. I'll follow that up in another PR.
> maint: update smoke tests to test components

- .circleci/config.yml
- Makefile
- pkg/data/components/S3ArchiveExporter.yaml
- add smoke tests to CI
- update ci config to use machine executor so volume mounting works
- add steps to install Go and yq
- update smoke target in makefile to not check for yq (this step wasn't working in ci)
- update smoke target in makefile to pass in the ya string in 1 line (ci didn't like splitting the string into separate lines).
> maint: add smoke tests to CI

- pkg/hpsf/hpsfTypes.go
- pkg/translator/testdata/bad_hpsf/invalid_component_version.yaml
- pkg/translator/translator.go
- pkg/translator/translator_test.go
- Ensure that components loaded match the HPSF configuration
- This updates the validation path to check that any component version specified in the HPSF will be taken into consideration when looking up the component. The component map should probably be a map of maps to include multiple versions of the same component in the near future, but this is ok for now.
> feat: add validation for component version

- cmd/hpsf/main.go
- go.mod
- pkg/config/component.go
- pkg/config/refinery.go
- pkg/config/templateComponent.go
- pkg/hpsftypes/go.mod
- pkg/hpsftypes/types.go
- pkg/translator/translator.go
- pkg/translator/translator_test.go
- tests/go.mod
- tests/providers/hpsf/hpsf_provider.go
- This reduces the dependency on the config package, as currently the usage of `hpsf/pkg/config` is limited to the types of artifacts defined within that package. This will allow us to scope down the public api in the near future, reducing the surface 
of changes that will need to be tested to support multiple versions.
- added `hpsftypes` package
- deprecate types in the config package in favour of the types defined in hpsftypes
> feat: split up hpsftypes into separate package

- pkg/data/loadEmbedded.go
- pkg/translator/translator_test.go
- Continuing to reduce the API surface, this change removes a function that was only used in a test file, and replaced its usage by calling LoadEmbeddedTemplates directly.
- Removes `LoadEmbeddedDefaultTemplate`
- Update tests using it
> chore: remove unused function LoadEmbeddedDefaultTemplate

- pkg/config/component.go
- pkg/config/refinery.go
- pkg/translator/translator_test.go
- tests/go.mod
- tests/go.sum
These have been updated in all downstream dependencies
> chore: remove deprecated consts

- pkg/data/components/FieldContainsCondition.yaml
- pkg/data/components/FieldStartsWithCondition.yaml
- pkg/translator/testdata/hpsf/fieldcontainscondition_all.yaml
- pkg/translator/testdata/hpsf/fieldcontainscondition_defaults.yaml
- pkg/translator/testdata/hpsf/fieldstartswithcondition_all.yaml
- pkg/translator/testdata/hpsf/fieldstartswithcondition_defaults.yaml
- pkg/translator/testdata/refinery_rules/fieldcontainscondition_all.yaml
- pkg/translator/testdata/refinery_rules/fieldcontainscondition_defaults.yaml
- pkg/translator/testdata/refinery_rules/fieldstartswithcondition_all.yaml
- pkg/translator/testdata/refinery_rules/fieldstartswithcondition_defaults.yaml
- pkg/translator/translator_test.go
- Adds two new conditions to Refinery rules components:
- `FieldStartsWithCondition` checks a string field for a prefix
- `FieldContainsCondition` checks a string field for a prefix
- Create components
- Create a new condition test function that can quickly test all condition objects
- Add test files where needed
> feat: Add FieldStartsWith and FieldContains conditions

- cmd/hpsf/main.go
- pkg/hpsf/hpsfTypes.go
- pkg/translator/translator_test.go
- tests/providers/hpsf/hpsf_provider.go
- Adding `library_version` field to store the version of the library that was used when generating HPSF. This version will be used later on when using different versions of the library to translate HPSF into various configurations.
- Introduce a `FromYAML` func to use downstream
- add LibraryVersion struct field 
- add FromYAML func and clean up various areas where decoding was done
> feat: add library_version field, add FromYAML func

- pkg/hpsf/hpsfTypes.go
- pkg/hpsf/hpsfTypes_test.go
- pkg/translator/translator.go
- pkg/validator/validator.go
This function is only ever used internally within the hpsf package, no need for a public function.
> refactor: remove EnsureYAML public func

- pkg/data/components/EMADynamicSampler.yaml
- pkg/translator/testdata/hpsf/emadynamicsampler_all.yaml
- pkg/translator/testdata/refinery_rules/emadynamicsampler_all.yaml
- pkg/translator/testdata/refinery_rules/emadynamicsampler_defaults.yaml
Updates the EMA dynamic sampler to add missing properties that are useful.
Builder view:
Generated config:
```yaml
RulesVersion: 2
Samplers:
__default__:
EMADynamicSampler:
GoalSampleRate: 100
AdjustmentInterval: 1m0s
Weight: 0.5
AgeOutValue: 0.5
BurstMultiple: 2
BurstDetectionDelay: 3
FieldList:
- http.status_code
MaxKeys: 500
```
- Add new properties to the sampler
- Update tests to verify expected behaviour
> feat: Add missing advanced properties to EMA dynamic sampler

- pkg/data/components/SamplingSequencer.yaml
- pkg/translator/translator.go
- pkg/translator/translator_paths_test.go
- pkg/translator/translator_test.go
- A user noticed that rules connected past rule 9 in the SamplingSequencer were being ordered after rule 1. In other words, the rules were being ordered by rule name instead of rule index. To fix this, we needed to extract the index information from the template component and make that available at the point where we order the rules.
- Implemented index‑aware path ordering: added helper and orderPaths logic so SampleData (and other) paths sort first by port index, then existing tie‑breakers.
- Updated SamplingSequencer component definition so its 12 rule output ports use explicit sequential indexes 1–12 (was including 0/unspecified before), ensuring “Rule 12” reliably sorts last.
- Added a comprehensive ordering test that builds a full SamplingSequencer topology with 12 distinct rule …
> fix(poodle, pipelines): Make rules order according to rule index
