- Makefile
- making CI/dev work easier
- Adding makefile w/ test target.
> maint: add Makefile

- Makefile
- go.mod
- go.sum
- pkg/config/components/honeycombExporter.yaml
- pkg/config/loadComponents_test.go
- pkg/config/testdata/HoneycombExporter_output_refinery_config.yaml
- This adds a test and fixes the template for the honeycomb exporter.
> maint: add test for validating honeycomb exporter output

- .circleci/config.yml
- .gitignore
- Improvements to dev and CI
- ignore test results generated in dev env
- upload test results to CI jobs
> ci: display test results in Circle; ignore them in dev

- pkg/config/components/FilterProcessor.yaml
- pkg/translator/testdata/http_collector_config_with_filter_processor.yaml
- pkg/translator/testdata/http_hpsf_with_filtering.yaml
- pkg/translator/translator_test.go
- This PR adds a component for supporting filtering.
- added the component yaml, as well as testing for the output w/ a collector
> feat(filtering): add filtering processor

- .circleci/config.yml
- Makefile
- examples/hpsf2.yaml
- examples/hpsfBig.yaml
This will ensure that changes made to the code will work with the examples listed in the examples directory.
> fix: add a step to validate all examples in CI

- .circleci/config.yml
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- RELEASING.md
- SECURITY.md
- SUPPORT.md
- This repository should be releaseable under our standard style, with a version number. This adds those artifacts and preps for release v0.1.0.
> maint: Do the things to make this repo releaseable.

- pkg/config/tmpl/collectorconfig.go
- pkg/config/tmpl/collectorconfig_test.go
- pkg/translator/testdata/default_collector_config.yaml
- pkg/translator/testdata/http_collector_config_with_filter_processor.yaml
- pkg/translator/testdata/otlp_with_debug_exporter_collector_config.yaml
- pkg/translator/testdata/simple_grpc_collector_config.yaml
- pkg/translator/testdata/simple_grpc_collector_config_with_headers.yaml
- pkg/translator/testdata/simple_http_collector_config.yaml
- pkg/translator/testdata/simple_http_collector_config_with_headers.yaml
- pkg/translator/testdata/simple_http_collector_config_with_headers_insecure.yaml
- Batching should be part of the pipeline by default.
- Automatically append the batch processor to the generated list of processors. This will be changed in the near future
> feat: add batch processor automatically

- pkg/config/templateComponent.go
- pkg/data/components/DeterministicSampler.yaml
- pkg/data/components/EmaThroughput.yaml
- pkg/data/components/HoneycombExporter.yaml
- pkg/data/components/OTelDebugExporter.yaml
- pkg/data/components/OTelHTTPExporter.yaml
- pkg/data/components/TraceConverter.yaml
- pkg/data/loadEmbedded_test.go
- This adds the alpha status for components, and marks some of the components as alpha.
- adding status
- updating component config to set status level
> feat: add alpha status

- pkg/data/components/LogDeduplicationProcessor.yaml
- pkg/translator/testdata/otlp_with_logdeduplication_collector_config.yaml
- pkg/translator/testdata/otlp_with_logdeduplication_hpsf.yaml
- pkg/translator/translator_test.go
- This will allow deduplication of logs via a collector.
- add component template
- add test to validate component usage is correct
> feat: add log deduplication processor

- CHANGELOG.md
- version.go
Prepares the v0.2.0 release of this package.
- Add changelog entry
- Add version file so users know the package version
> rel: Prepare release v0.2.0

- pkg/data/components/LogDeduplicationProcessor.yaml
- The dedup processor needs an output.
> fix: add output config to processor

- CHANGELOG.md
- version.go
- new release with alpha components and updated default template
- update changelog
- update version
> rel: prep release v0.4.0

- pkg/config/templateComponent.go
- pkg/data/components/NopReceiver.yaml
- pkg/data/components/S3Exporter.yaml
- hpsf needs to deliver the logo field as part of the data in a component
- Add logo to the templateComponent
- fix direction of NopReceiver (ports for receivers are output ports)
- s3exporter needs the AWSS3 icon
> feat: add logo, fix a couple components

- CHANGELOG.md
- version.go
> Prep v0.5.0

- .github/workflows/add-to-project-v2.yml
- .github/workflows/validate-pr-title.yml
- Adding these to be consistent w/ other repos.
> maint: add github workflows

- pkg/data/components/TraceConverter.yaml
- pkg/translator/testdata/collector_config/traceconverter_all.yaml
- pkg/translator/testdata/collector_config/traceconverter_defaults.yaml
- traceconverter batch settings are not nested correctly
- nest under `batch`.
> fix: traceconverter batch settings

- pkg/config/templateComponent.go
- The templates section of components is an array, and was always intended to allow multiple templates per component, but the implementation assumed only one. This fixes that so it's possible to have multiple, which makes it so that we can build components that modify more than one collector component.
- Don't early exit from GenerateConfig, accumulate the results and merge them at the end.
> fix: make it possible to have multiple templates per kind

- examples/hpsf.yaml
- examples/hpsf2.yaml
- examples/hpsfComposedComponents.yaml
- pkg/data/components/DeterministicSampler.yaml
- pkg/data/components/EmaThroughput.yaml
- pkg/data/components/HoneycombExporter.yaml
- pkg/data/components/KeepErrors.yaml
- pkg/data/templates/emathroughput.yaml
- pkg/data/templates/s3.yaml
- pkg/hpsf/hpsfTypes_test.go
- pkg/translator/testdata/hpsf/deterministicsampler_all.yaml
- pkg/translator/testdata/hpsf/deterministicsampler_defaults.yaml
- pkg/translator/testdata/hpsf/emathroughput_all.yaml
- pkg/translator/testdata/hpsf/emathroughput_defaults.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
- pkg/translator/testdata/hpsf/honeycombexporter_defaults.yaml
- pkg/translator/testdata/hpsf/keeperrors_all.yaml
- pkg/translator/testdata/hpsf/keeperrors_defaults.yaml
- pkg/translator/testdata/hpsf/parseattributeasjson_all.yaml
- pkg/translator/testdata/hpsf/parseattributeasjson_defaults.yaml
- pkg/translator/testdata/hpsf/samplebyhttpstatus_all.yaml
- pkg/translator/testdata/hpsf/samplebyhttpstatus_defaults.yaml
- pkg/translator/testdata/hpsf/samplebytraceduration_all.yaml
- pkg/translator/testdata/hpsf/samplebytraceduration_defaults.yaml
- pkg/translator/testdata/hpsf/startsampling_all.yaml
- pkg/translator/testdata/hpsf/startsampling_defaults.yaml
- tests/scenario_tests/testdata/keep_errors.yaml
- tests/scenario_tests/testdata/parseattributeasjson_processor_custom.yaml
- tests/scenario_tests/testdata/parseattributeasjson_processor_defaults.yaml
- tests/scenario_tests/testdata/parseattributeasjson_processor_span.yaml
Consistency in naming of the ports across components.
All naming is now Traces, Logs, Metrics and Events across all ports.
> feat: Renamed all Port names and types

- CHANGELOG.md
- test.yaml
> rel: prep for v0.6.0

- CHANGELOG.md
- version.go
> rel: Prep v0.8.0

- CHANGELOG.md
- version.go
Prepares the next release of the HPSF package.
- Add changelog entry
- Update version to 0.9.0
> rel: Prepare 0.9.0 release

- CHANGELOG.md
- version.go
> rel: Prep v0.10.0

- CHANGELOG.md
- version.go
> rel: Prep v0.11.0

- CHANGELOG.md
- version.go
> rel: prep v0.12.0 release

- CHANGELOG.md
- version.go
> rel: prepare v0.13.0 release

- CHANGELOG.md
- version.go
- release a hotfix for Honeycomb exporter template
- update changelog and bump version
> rel: prepare v0.11.1 hotfix

- CHANGELOG.md
- version.go
> rel: prep v0.14.0 release

- pkg/translator/testdata/bad_hpsf/missing_condition_on_lower_index.yaml
- pkg/translator/testdata/bad_hpsf/valid_condition_on_lower_index.yaml
- pkg/translator/translator.go
- pkg/translator/translator_test.go
- The sampler component redesign needed to turn off some validations. This fixes them.
- Update sampler connection validations
- Fix some tests
> fix: Better sampler validation (conforms to new sampler design).

- CHANGELOG.md
- version.go
> rel: Prep v0.16.0 and also clean up previous changelog

- pkg/data/components/ExtractLogAttributesProcessor.yaml
- pkg/translator/testdata/collector_config/extractlogattributesprocessor_all.yaml
- pkg/translator/testdata/collector_config/extractlogattributesprocessor_defaults.yaml
- pkg/translator/testdata/hpsf/extractlogattributesprocessor_all.yaml
- pkg/translator/testdata/hpsf/extractlogattributesprocessor_defaults.yaml
- tests/scenario_tests/extract_log_attributes_test.go
- tests/scenario_tests/testdata/extract_log_attributes.yaml
Adds a new component that can extract log fields and merge them into log attributes. It has an optional field property that will be used to extract from in the log body if set.
- closes https://github.com/honeycombio/pipeline-team/issues/601
- Add new processor
- Add unit tests
- Add scenario test
> feat: Add extract log attributes processor

- CHANGELOG.md
- version.go
Prepares the next release of the package.
- Add changelog entry
- Update version to 0.19.0
> rel: Prepare v0.19.0 release

- CHANGELOG.md
- version.go
> rel: Prep v0.20.0
